language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - node
  - 10
script:
  - export NODE_ENV=test
  - npm run build
  - npm run test
  - npm run lint
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 70
after_success:
  - export NODE_ENV=production
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
